---
title: ज़ोंबी (Zombie) कहाँ है?
hero_image: images/banner.png
description: फ़ोन पे जीपीएस (GPS) का उपयोग घर के बाहर ज़ोंबी का गेम खेलने के लिए करे। आपूर्तियाँ (supplies) इकट्ठा करे और ज़ोंबी (Zombie) से बचे!
theme: yellow #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-1
interests: games
technologies: html-css-javascript
hardware: ''
software: html-css-javascript
site_areas: projects
version: 4
last_tested: 2017-09-01
steps:
  - 
    title: परिचय
  - 
    title: आपको किन चीजों की जरूरत होगी
  - 
    title: नक़्शे को बनाइये
  - 
    title: मार्कर डेटा को पुनः प्राप्त कीजिये/बचाइए
  - 
    title: निशान/मार्करस बनाइये
  - 
    title: अपना वर्तमान/मौजूदा स्थान दिखाइए/प्रदर्शित कीजिये
  - 
    title: देखिये यदि जीपीएस(GPS) काम कर रहा है या नही
  - 
    title: स्माइलीज का हमला
  - 
    title: वस्तुओ को ढूंढिए/खोजिये
  - 
    title: खेल(game) खेलते समय सुरक्षा
  - 
    title: "चुनौती: गेम में सुधार करें"
