---
title: Where's Zombie?
hero_image: images/banner.png
description: Use GPS on your phone to play an outdoor zombie game. Collect the supplies but avoid the zombies!
theme: yellow #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-1
interests: games
technologies: html-css-javascript
hardware: ''
software: html-css-javascript
site_areas: projects
version: 4
last_tested: 2017-09-01
steps:
  - 
    title: Introduction
  - 
    title: What you will need
  - 
    title: Create the map
  - 
    title: Retrieve the marker data
  - 
    title: Create the markers
  - 
    title: Display your current position
  - 
    title: Test the GPS
  - 
    title: Attack of the smileys
  - 
    title: Find the items
  - 
    title: Safety when playing the game
  - 
    title: "Challenge: improve the game"
